### ISSUE TITLE
audiowmark build failure

### ISSUE THREAD

**Issue by micwoj92** [osam-cologne/archlinux-proaudio#467]
Upstream issue: https://github.com/swesterfeld/audiowmark/issues/62
```
==> Starting build()...
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for gcc... gcc
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
/usr/bin/grep: warning: stray \ before -
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for sndfile... yes
checking for libmpg123... yes
checking for ld... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking for shared library run path origin... done
checking 32-bit host C ABI... no
checking how to run the C preprocessor... gcc -E
checking for ELF binary format... yes
checking for the common suffixes of directories in the library search path... lib,lib,lib64
checking for libzita-resampler... yes
checking how to link with libzita-resampler... /usr/lib/libzita-resampler.so
checking for fftw3f... yes
checking whether FFTW is recent enough... yes
checking for libgcrypt-config... no
checking for LIBGCRYPT - version >= 1.2.0... no
checking for libavcodec libavformat libavutil libswresample... yes
checking whether g++ supports C++14 features with -std=gnu++14... yes
checking whether C++ compiler accepts -Wall... yes
checking whether C++ compiler accepts -pthread... yes
checking whether make supports nested variables... (cached) yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating tests/test-common.sh
config.status: creating docs/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

---------------------------------------------------------------------------
audiowmark 0.6.2
---------------------------------------------------------------------------
  Use address sanitizer. . . . . . . .: no (for debugging)
  Use undefined behaviour sanitizer. .: no (for debugging)
  Use thread sanitizer . . . . . . . .: no (for debugging)
  Use leak sanitizer . . . . . . . . .: no (for debugging)
  Use stdc++ debug mode. . . . . . . .: no (for debugging)
  Use ffmpeg libs. . . . . . . . . . .: yes (use --with-ffmpeg to enable, required for HLS)
  Build developer documentation  . . .: no (use --with-docs to enable)
make  all-recursive
make[1]: Entering directory '/build/audiowmark/src/audiowmark-0.6.2'
Making all in src
make[2]: Entering directory '/build/audiowmark/src/audiowmark-0.6.2/src'
  CXX      audiowmark.o
  CXX      utils.o
  CXX      convcode.o
  CXX      random.o
  CXX      wavdata.o
  CXX      audiostream.o
  CXX      sfinputstream.o
  CXX      stdoutwavoutputstream.o
  CXX      sfoutputstream.o
  CXX      rawinputstream.o
  CXX      rawoutputstream.o
  CXX      rawconverter.o
  CXX      mp3inputstream.o
  CXX      wmcommon.o
  CXX      fft.o
  CXX      limiter.o
  CXX      shortcode.o
  CXX      mpegts.o
  CXX      hls.o
  CXX      wmget.o
  CXX      wmadd.o
  CXX      syncfinder.o
  CXX      wmspeed.o
  CXX      threadpool.o
  CXX      resample.o
  CXX      hlsoutputstream.o
  CXX      testconvcode.o
  CXX      testrandom.o
  CXX      testmp3.o
  CXX      teststream.o
hlsoutputstream.cc: In member function ‘Error HLSOutputStream::add_stream(const AVCodec**, AVCodecID)’:
hlsoutputstream.cc:116:26: error: ‘av_get_channel_layout’ was not declared in this scope; did you mean ‘set_channel_layout’?
  116 |   uint64_t want_layout = av_get_channel_layout (m_channel_layout.c_str());
      |                          ^~~~~~~~~~~~~~~~~~~~~
      |                          set_channel_layout
hlsoutputstream.cc:119:10: error: ‘AVCodecContext’ {aka ‘struct AVCodecContext’} has no member named ‘channel_layout’; did you mean ‘ch_layout’?
  119 |   m_enc->channel_layout = want_layout;
      |          ^~~~~~~~~~~~~~
      |          ch_layout
hlsoutputstream.cc:120:17: error: ‘const AVCodec’ {aka ‘const struct AVCodec’} has no member named ‘channel_layouts’; did you mean ‘ch_layouts’?
  120 |   if ((*codec)->channel_layouts)
      |                 ^~~~~~~~~~~~~~~
      |                 ch_layouts
hlsoutputstream.cc:122:14: error: ‘AVCodecContext’ {aka ‘struct AVCodecContext’} has no member named ‘channel_layout’; did you mean ‘ch_layout’?
  122 |       m_enc->channel_layout = (*codec)->channel_layouts[0];
      |              ^~~~~~~~~~~~~~
      |              ch_layout
hlsoutputstream.cc:122:41: error: ‘const AVCodec’ {aka ‘const struct AVCodec’} has no member named ‘channel_layouts’; did you mean ‘ch_layouts’?
  122 |       m_enc->channel_layout = (*codec)->channel_layouts[0];
      |                                         ^~~~~~~~~~~~~~~
      |                                         ch_layouts
hlsoutputstream.cc:123:33: error: ‘const AVCodec’ {aka ‘const struct AVCodec’} has no member named ‘channel_layouts’; did you mean ‘ch_layouts’?
  123 |       for (int i = 0; (*codec)->channel_layouts[i]; i++)
      |                                 ^~~~~~~~~~~~~~~
      |                                 ch_layouts
hlsoutputstream.cc:125:25: error: ‘const AVCodec’ {aka ‘const struct AVCodec’} has no member named ‘channel_layouts’; did you mean ‘ch_layouts’?
  125 |           if ((*codec)->channel_layouts[i] == want_layout)
      |                         ^~~~~~~~~~~~~~~
      |                         ch_layouts
hlsoutputstream.cc:126:22: error: ‘AVCodecContext’ {aka ‘struct AVCodecContext’} has no member named ‘channel_layout’; did you mean ‘ch_layout’?
  126 |               m_enc->channel_layout = want_layout;
      |                      ^~~~~~~~~~~~~~
      |                      ch_layout
hlsoutputstream.cc:129:29: error: ‘AVCodecContext’ {aka ‘struct AVCodecContext’} has no member named ‘channel_layout’; did you mean ‘ch_layout’?
  129 |   if (want_layout != m_enc->channel_layout)
      |                             ^~~~~~~~~~~~~~
      |                             ch_layout
hlsoutputstream.cc:131:10: error: ‘AVCodecContext’ {aka ‘struct AVCodecContext’} has no member named ‘channels’
  131 |   m_enc->channels = av_get_channel_layout_nb_channels (m_enc->channel_layout);
      |          ^~~~~~~~
hlsoutputstream.cc:131:63: error: ‘AVCodecContext’ {aka ‘struct AVCodecContext’} has no member named ‘channel_layout’; did you mean ‘ch_layout’?
  131 |   m_enc->channels = av_get_channel_layout_nb_channels (m_enc->channel_layout);
      |                                                               ^~~~~~~~~~~~~~
      |                                                               ch_layout
  CXX      testlimiter.o
hlsoutputstream.cc:131:21: error: ‘av_get_channel_layout_nb_channels’ was not declared in this scope
  131 |   m_enc->channels = av_get_channel_layout_nb_channels (m_enc->channel_layout);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hlsoutputstream.cc: In member function ‘AVFrame* HLSOutputStream::alloc_audio_frame(AVSampleFormat, uint64_t, int, int, Error&)’:
hlsoutputstream.cc:154:10: error: ‘AVFrame’ {aka ‘struct AVFrame’} has no member named ‘channel_layout’; did you mean ‘ch_layout’?
  154 |   frame->channel_layout = channel_layout;
      |          ^~~~~~~~~~~~~~
      |          ch_layout
hlsoutputstream.cc: In member function ‘Error HLSOutputStream::open_audio(const AVCodec*, AVDictionary*)’:
hlsoutputstream.cc:192:62: error: ‘AVCodecContext’ {aka ‘struct AVCodecContext’} has no member named ‘channel_layout’; did you mean ‘ch_layout’?
  192 |   m_frame     = alloc_audio_frame (m_enc->sample_fmt, m_enc->channel_layout, m_enc->sample_rate, nb_samples, err);
      |                                                              ^~~~~~~~~~~~~~
      |                                                              ch_layout
hlsoutputstream.cc:196:62: error: ‘AVCodecContext’ {aka ‘struct AVCodecContext’} has no member named ‘channel_layout’; did you mean ‘ch_layout’?
  196 |   m_tmp_frame = alloc_audio_frame (AV_SAMPLE_FMT_FLT, m_enc->channel_layout, m_enc->sample_rate, nb_samples, err);
      |                                                              ^~~~~~~~~~~~~~
      |                                                              ch_layout
hlsoutputstream.cc:215:66: error: ‘AVCodecContext’ {aka ‘struct AVCodecContext’} has no member named ‘channels’
  215 |   av_opt_set_int        (m_swr_ctx, "in_channel_count",   m_enc->channels,       0);
      |                                                                  ^~~~~~~~
hlsoutputstream.cc:218:66: error: ‘AVCodecContext’ {aka ‘struct AVCodecContext’} has no member named ‘channels’
  218 |   av_opt_set_int        (m_swr_ctx, "out_channel_count",  m_enc->channels,       0);
      |                                                                  ^~~~~~~~
  CXX      testshortcode.o
make[2]: *** [Makefile:853: hlsoutputstream.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/build/audiowmark/src/audiowmark-0.6.2/src'
make[1]: *** [Makefile:432: all-recursive] Error 1
make[1]: Leaving directory '/build/audiowmark/src/audiowmark-0.6.2'
make: *** [Makefile:364: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by SpotlightKid** [comment]
Thanks for the heads-up and the link to the upstream issue.

Let's wait a while to see whether this gets fixed upstream before we *maybe* try to fix this ourselves.

**Comment by micwoj92** [comment]
There are multiple solutions that can be done quickly before waiting for upstream:
- build without ffmpeg, will decrease functionality
- build using ffmpeg4.4 from Extra repo, haven't tested this
- build using older ffmpeg(presumably 6.x) from AUR. This will be worst for build overhead.

**Comment by SpotlightKid** [comment]
> * build using older ffmpeg(presumably 6.x) from AUR. This will be worst for build overhead.

We don#t support dependencies on the AUR, sorry.

**Comment by SpotlightKid** [comment]
This was fixed in upstream release 0.6.3: https://github.com/swesterfeld/audiowmark/pull/68
